### ISSUE TITLE
Thank You's

### ISSUE THREAD

**Issue by mattgraham** [mattgraham/frontendthanks#2]
![website thanks](https://cloud.githubusercontent.com/assets/51578/3897585/f07aa156-2262-11e4-8740-eb98bdb080bc.png)

I've grabbed a js script from codedrop to filter in and out the thank you messages. You'll see it on the /thanks pages now. Currently its pulling in json files; I'd like to change that to the markdown files in the posts directory with the added variables in the header of the file. You'll have to run the site locally to understand my thoughts; its very young in development.

**Comment by mattgraham** [comment]
As I'm starting to iron out thoughts I came up with this tonight (obviously this will change some of the site styles): 

![website thanks](https://cloud.githubusercontent.com/assets/51578/3929259/779588a8-241c-11e4-9300-119991834296.png)

![website thanks search](https://cloud.githubusercontent.com/assets/51578/3929260/7ade2844-241c-11e4-9366-80a6e14c15d9.png)

The drop down / search will open the tab (hopefully full of thank yous) and the characters at the bottom can randomly rotate in on load etc.

**Comment by chriscoyier** [comment]
THUMBS UP EMOTICON

**Comment by bencallahan** [comment]
sweet

**Comment by chriscoyier** [comment]
From Allison House:

This video: https://www.youtube.com/watch?v=sbpUBW_bo-0

**Comment by chriscoyier** [comment]
From Lea Alcantara:

> Dan is a class act from beginning to end—he treated all Front-End Design Conf speakers with a ton of respect and kindness. When United Airlines lost my luggage, Dan and co-organizer Cherrie were tireless in hounding the airport to correct what had happened. They even paid for and provided me with emergency essentials due to the luggage snafu. Beyond that, they were extraordinarily attentive to both speaker and attendee alike. They kept the event warm and friendly, and when I spoke, Front-End Conf had a majority female lineup but it was publicized like any regular conference—a testament that they were committed to quality speakers first and foremost. I think the participants in Front-End Design Conf understand this, and it’s with bittersweetness that I say good-bye to this great conference. Thank you Dan, Cherrie and the rest of the team that made Front-End Design Conf possible.

**Comment by chriscoyier** [comment]
From Andrea Graham:

> For six years, I’ve looked forward to spending a few rainy summer days immersed in the nerdy, creative community that is the Front End Design Conference.  To immersing myself in my craft; to socializing with my idols; to discovering new approaches; affirming my decisions and to partying with all of your bad selves.  And best of all - it was always just around the corner.  A cab ride away after the after-party, if you will...  
> 
> I’m gonna miss that. 
> 
> The thought and care you put into selecting speakers; the selflessness of your passion; the foresight into trends and up-and-comers; and most importantly, the incredibly personal way you make everyone think that you wanted them there above all else… 
> 
> I’m gonna miss that.  
> 
> Karaoke after-after parties, negotiating for drink tickets with non-drinkers, photo booth bombing, bacon everything of course, engaging conversations with my peers and colleagues, team-time with my staff, the glue of the Tampa Bay web community, the rain (OHSOMUCHRAIN) ...  
> 
> I’m gonna miss that.
> 
> Dan and Cherrie: thank you for being amazing organizers, kind and thoughtful people, and great friends. I just hope our annual reason to see each other doesn’t mean we never see each other again.

**Comment by chriscoyier** [comment]
Jason VanLue:

---

Dan Denney, how do I love thee? Let me count the ways:
1. Dan Is Generous — seriously, Dan is one of the most genuine, kind, and generous people I've come to know. He always thinks of others first, and himself last.
2. Dan Is Humble — he has every reason to brag, considering his contribution to, and his stature within, the web community. But he doesn't do that. Instead, he gives back over and over and over selflessly.
3. Dan Is Hard-Working — I had the privilege to offer Dan a job a couple years ago, and he continues to be one of the hardest workers in the company. He never complains, always goes above and beyond, and is a joy to work next to.

So Dan, I raise my glass to you (yes, I’m holding a drink right now, why do you ask?). Thanks for all you've done for me personally, and for our community at large. You deserve every honor that comes your way.

**Comment by chriscoyier** [comment]
Matthew Carver:

> I haven’t known Dan Denney for very long.  I met Dan just in time to get to see Front End Design Conference before it ended, but I’m incredibly fortunate for getting the opportunity.  Dan’s optimism, graciousness, and earnestness created the warmest community of people I’ve ever met in the people who attended his conferences.  The world is full of cynics, because it’s easy to be cynical.  Being a positive person is tough, but creating positivity in others is damn near a miracle.  Even though I only this year got to attend Front End Design Conference, I immediately recognized it as something incredibly special and it was only possible thanks to an incredible dude.

**Comment by chriscoyier** [comment]
Travis Miller:

> Who would've thought  Hip-hop and the Web would be a great topic at Front End Design Conference? Turns out I was lucky that Dan did. In most cases he turned out be a bigger Hip-hop enthusiast than me. More than I think he knows, Dan has been a great role model to me on and offline.  Dan gave me a chance to speak on something I was passionate about for the first time in front my peers and for that I'll forever be grateful.. Front End Design Conference on the whole has made me a better person in multiple aspects of my profession. I can't imagine where I'd be today without it.
> 
> I have no doubt that we're going to keep the spirit of the conference alive in one way or another (The Bahamas is still on the table haha).
> 
> I wish Dan, Cherrie and the entire family all the best. To many more years of moving the web forward!

**Comment by chriscoyier** [comment]
Jenn Lukas:

> Front End Design Conference was one of my most favoritest conferences I've ever spoken at! The talks, the attendees, the venue, it was all amazing. Also the opportunity to give more people the chance to share their knowledge with attendee-submitted talks cultivates an incredibly special community and experience. I know why this happens. Because of the amazing team that puts on this inclusive, welcoming, super unique conference. Cherrie and Dan are two of the raddest, most talented folks I know. Thanks for putting your hearts into a great conference and giving us all an opportunity to learn from each other and do the running man together. 

![img_6836](https://cloud.githubusercontent.com/assets/69156/3982463/0ec9a91c-2877-11e4-8a92-7dd19743e139.jpg)
![img_6842](https://cloud.githubusercontent.com/assets/69156/3982462/0ec8bd86-2877-11e4-87ba-c177b9794c5e.JPG)
![img_6868](https://cloud.githubusercontent.com/assets/69156/3982464/0ed2ac4c-2877-11e4-912e-7e656c157cfa.JPG)

**Comment by chriscoyier** [comment]
John Ashenden:

Put together a farewell video: https://www.youtube.com/watch?v=TwntfjS9GxA

**Comment by chriscoyier** [comment]
Ethan Marcotte:

> I was lucky enough to speak at Front End [a few years back](http://frontenddesignconference.com/2011), and was immediately struck by how warm everything was. Okay, no: not the weather. (Though hey, St. Petersburg _was_ looking rather stunning.) Really, the warmth was coming from everything else: the speakers were brilliant and passionate; the theater was breathtaking; and the attendees were smiling, thoughtful, and, well, _nice_.
> 
> And a large part of that warmth was due to Dan’s hard work. He and Cherrie managed to bring some of the nicest people I’d ever met into one space, packed it full of informative, insightful talks, and infused it with their love of the web. Front End was one of my favorite events I’ve spoken at—and while I’m sad I won’t get a chance to go back, I’m so excited to see what Dan and Cherrie do next.
> 
> Dan, Cherrie: thank you.

**Comment by chriscoyier** [comment]
Cameron Moll:

> Dan and Cherrie are two of the most generous, caring people I know of
> in our industry. There's no doubt in my mind they poured every ounce
> of love they possibly could into every Front End Design Conference.
> I'll always remember the address I gave in 2013, not because it was my
> best but because it was so warmly received by the audience. Clearly
> that's a reflection of the caliber of people they attract, and I'm
> honored to be one of those.

**Comment by chriscoyier** [comment]
Andrew Norcross:

> I had attended the St. Petersburg conference a few times, and gotten to know Dan and Cherry personally. I’m honored that I can call them my friends.
> 
> This year, I was given the opportunity to speak at the final St. Petersburg conference. Having attended in the past, I knew the caliber of speakers that Dan gets each year, so it was humbling (to say the least) to be included with such company. The event has been top-notch every time, with the little perks (chocolate bacon, anyone?) that easily made it my favorite conference to attend each year.

**Comment by chriscoyier** [comment]
Tweets a good idea too? These from the site are good:

https://twitter.com/olivierlacan/statuses/488039051531149314
https://twitter.com/imbradmiller/statuses/488310883181793281

**Comment by bencallahan** [comment]
@chriscoyier I assume we need to get these converted to MD and put into the `/_thanks` folder?

Also, love the idea of using some tweets...

**Comment by garand** [comment]
I think @mattgraham is on it.

**Comment by garand** [comment]
He's typing away frantically over here.

**Comment by mattgraham** [comment]
@bencallahan yeah I'm working on adding them in now. Then I have a few jekyll bugs and will need some js help to make it snazzy.

**Comment by chriscoyier** [comment]
Jason Beaird:

> You know, I really only wanted to attend the conference and somehow I managed to get myself on stage this year in St. Pete. As I said before my talk, I had known about Front-End since the very beginning and my only regret (aside from that whole being on stage thing) is that I didn't make it to one before 2014. The event was everything I expected from what I had heard about previous years and a whole lot more. I've been to a lot of conferences and the camaraderie, humility and passion of everyone present made it unlike any other. I know first-hand that this kind of community doesn't just happen overnight. Dan, Cherrie and the rest of the Front-End Design Conference team have undoubtedly cultivated something magical and regardless of whether the conference goes on, the world (& the web) is a better place because of it. I'm thankful that I finally had the opportunity to be a part of the fun, supportive, amazing - and now, legendary - #frontendconf family.

**Comment by chriscoyier** [comment]
Andrew Maier:

> Dear Dan,
> 
> Thanks so much for taking a chance on me as a speaker for your inaugural Front End Design conference. That experience was honestly the first time I'd ever spoken in front of so many people at a professional design event. It really gave me the shock I needed to begin taking speaking seriously and double down on my commitment to user experience design. People like you do so much for our community, so much for the fledgling designers that really want to make a difference in the world and just need a chance to be heard. Keep kicking ass and changing lives.
> 
> Your friend,
> Andrew Maier
> Current Code for America Fellow and
> Former Editor-in-Chief, UX Booth

**Comment by mattgraham** [comment]
Alright, the plan is to hopefully ship the first version of this site tonight; there are a few more things that need to happen for responsive nav etc. but I think the rest is shippable.

In the next few days I'll work on the sortable searching, dropdown list, etc. for now however, its good to go. 

I'm going to close this issue and as we have additional thanks messages we can add issues for each.
