### ISSUE TITLE
Day Of The Event

### ISSUE THREAD

**Issue by chriscoyier** [mattgraham/frontendthanks#7]
As @bencallahan suggested to me, we should do something on the day of the event. 

I'd be willing to cut into my talk a bit to do a formal "on stage" thanking. We'd probably make it quick. 
1. Everybody (all speakers at the event, and any past speakers who are there) rush up onto the stage.
2. We do a quick speech thanking Dan, Cherrie, and all the FED crew.
3. We show the thank-you website on the big screen
4. We announce the t-shirt and encourage attendees to support
5. We all bow down and go all [we're not worthy](https://www.youtube.com/watch?v=-FucbvoFFy0) on them.

3:30pm?

**Comment by bencallahan** [comment]
Awesome, Chris—thanks for putting this together! Wondering if it would be more impactful to do this at the very end? I’m sure Jason would give us 5 or 10 of his minutes.

I do still think it should be you coming up to facilitate, though... You’re like the FED Conference mascot.

![Chris](http://media0.giphy.com/media/avbhNoyfnrlmw/200.gif)

**Comment by chriscoyier** [comment]
Yeah end is probably best. I just didn't want to volunteer anyone's time but my own. Let's email Jason and see if he's cool with it. Or maybe it doesn't even matter because it's the end? We'll just kinda rush the stage?

**Comment by mattgraham** [comment]
Love this idea. I currently don't have a ticket/hotel to get there but the more we talk about this I feel crazy sad to not be there.

**Comment by chriscoyier** [comment]
Oh shit I didn't realize you weren't going to be there. I'll donate a hotel room for you, would that help make it possible?

**Comment by bencallahan** [comment]
@mattgraham are you gonna make it?

**Comment by mattgraham** [comment]
Sadly no. We might have to put a photo of my face in one of your talks with a big. "Matt Graham loves Dan and Cherrie" 

:(
—

**Comment by mattgraham** [comment]
Thinking this through, if we launch the site tomorrow; these issues will become public. We can attempt to delete them or we can stall the launch. Thoughts?

**Comment by chriscoyier** [comment]
Can't we just leave the repo private? gh-pages sites are live either way, right?

**Comment by mattgraham** [comment]
We can, we'll just loose the ability for them to contribute via pull-requests / issues if we do that.

**Comment by chriscoyier** [comment]
And the danger of making the issues public is that it spoils the surprise?

**Comment by garand** [comment]
Have you guys considered making this site anonymous?

**Comment by mattgraham** [comment]
I don't see any advantage of it being anonymous. I'm sure dan will want to respond etc being the guy he is. Do you see something different?—

**Comment by chriscoyier** [comment]
I'd say just leave the repo private until the unveiling on (Friday?) then make it public.

Can I help with the JS stuff?

**Comment by mattgraham** [comment]
Absolutely. 
—

**Comment by mattgraham** [comment]
I'm :+1: on holding off on launching the site until Friday, I'll publish it in the morning and whenever your on stage you can bring it up. Hopefully it will stir up some traffic for those there as well as those who've attended St. Petersburg events.
