### ISSUE TITLE
Quick Preview of the Tribute T for Dan and Cherrie

### ISSUE THREAD

**Issue by bencallahan** [mattgraham/frontendthanks#8]
Hey all,

Thought I’d toss a quick glimpse of the shirt in here. After going 'round and 'round, we decided to take it a completely different way. Not having all the illustrations made it tough to do something that felt right. Also, we wanted to potentially reach a broader audience with the shirt. So, here it is. The back has a very small, "Thank you Dan and Cherrie" with the Frontend Design Conf logo.

Shirt title:
Give Back

Shirt Description:
Dan Denney has exemplified “giving back” by organizing Frontend Design Conf for the past six years. If you’ve had the opportunity to attend this event, you know it’s truly been about the community. Since this is the last year for Frontend Design Conf, we want to offer this shirt as a reminder of what it is that makes this industry beautiful. All profit will go to Dan and Cherrie as a “Thank You” for their hard work. Buy a shirt. Give back.

![frontend tee](https://cloud.githubusercontent.com/assets/539359/3971962/8df55f82-27d8-11e4-99f5-8328b148293b.jpg)

**Comment by chriscoyier** [comment]
lovely

**Comment by garand** [comment]
:thumbsup: :ok_hand: :heart:

**Comment by mattgraham** [comment]
Love it!

**Comment by bencallahan** [comment]
Decided to go black:

![vmxelxfcxiiifvjarqqbingm9oag_wcsljq-yskbfq4](https://cloud.githubusercontent.com/assets/539359/4002711/569f177e-296f-11e4-9baa-1aa963888cfa.jpg)

Should be going live tomorrow afternoon.

**Comment by mattgraham** [comment]
Shipped!
